apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
stringData:
  sa-password: "IS7egohDohxai7ahfooweiy.ahl1shei"
  connectionstring: "Data Source=octopetshop-sqlserver-cluster-ip-service;Initial Catalog=OctoPetShop; User ID=sa; Password=IS7egohDohxai7ahfooweiy.ahl1shei"
